-- GENERATED by scripts/bundle-schema.mjs — all FirstEmployer migrations in order.
-- Paste into the Supabase SQL editor of a fresh project and run once.
-- Excludes the PGlite test shim (Supabase already provides auth.uid() etc.).

-- ============================================================
-- 0001_enums_and_helpers.sql
-- ============================================================
-- 0001 — shared enums and helper functions
-- FirstEmployer schema foundation. Applies cleanly to Supabase Postgres and to
-- the PGlite test harness (which pre-loads an auth shim; see supabase/tests/).
-- gen_random_uuid() is built into Postgres core (>= 13), so no extension is
-- required for UUID defaults.

-- ============================================================
-- Shared enums (domain vocabulary — CLAUDE.md §5)
-- ============================================================
create type business_type as enum ('sole_trader', 'limited');
create type tier as enum ('starter', 'launch', 'growth');
create type subscription_state as enum ('trialing', 'active', 'past_due', 'canceled');

create type pay_period as enum ('hourly', 'weekly', 'four_weekly', 'monthly', 'annual');
create type employee_status as enum ('prospective', 'active', 'left');

create type determination_verdict as enum ('employee', 'worker', 'self_employed');
create type confidence_band as enum ('clear', 'leaning', 'ambiguous');

create type config_status as enum ('draft', 'scheduled', 'live', 'superseded');

create type document_type as enum (
  'employment_contract',   -- written statement of particulars
  'offer_letter',
  'new_starter_checklist',
  'variation_letter',      -- uprating / pay-change consolidated statement
  'status_determination',  -- determination PDF (mirrored as a document artefact)
  'rtw_statutory_excuse'
);
create type document_status as enum ('draft', 'examining', 'approved', 'human_review', 'superseded');

create type examination_verdict as enum ('pass', 'fail');

create type obligation_type as enum (
  'employment_status',
  'written_statement',
  'hmrc_paye',
  'payroll',
  'pension_enrolment',
  'pension_declaration',
  'el_insurance',
  'right_to_work',
  'minimum_wage',
  'ico_registration',
  'health_safety',
  'record_keeping'
);
create type obligation_state as enum ('not_started', 'in_progress', 'blocked', 'complete', 'at_risk', 'overdue');

create type rtw_route as enum ('manual', 'share_code', 'employer_checking_service');
create type rtw_result as enum ('pass', 'follow_up_required', 'fail');

-- retention_class governs deletion behaviour on account closure (skill gotcha #3):
-- statutory-retention rows survive owner anonymisation.
create type retention_class as enum (
  'standard',              -- deletable with the account
  'rtw_employment_plus_2y',
  'holiday_pay_6y'
);

create type event_actor_kind as enum ('user', 'system', 'admin', 'examiner', 'generator');

-- ============================================================
-- Helper: updated_at maintenance (mutable tables only)
-- ============================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- Helper: hard immutability (evidence tables — CLAUDE.md Rule 5)
-- Blocks UPDATE and DELETE for EVERY role, including the table owner and
-- service_role. RLS alone cannot stop service_role; this trigger can.
-- ============================================================
create or replace function public.forbid_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'Row is immutable: % on % is not permitted (append-only evidence table)',
    tg_op, tg_table_name
    using errcode = 'restrict_violation';
  return null;
end;
$$;

-- Note: the tenant-RLS helper functions (is_member_of, employee_business,
-- document_business) reference tables created in later migrations, and
-- `language sql` bodies are validated at creation time, so they are defined in
-- 0006 alongside the policies that use them.

-- ============================================================
-- 0002_core_tables.sql
-- ============================================================
-- 0002 — core tenant tables: profiles, businesses, membership, employees

-- profiles: 1:1 extension of auth.users
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  -- On account deletion we anonymise rather than hard-delete where statutory
  -- retention applies (skill gotcha #3). This flag records that state.
  anonymised boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- businesses: the tenant. type drives checklist instantiation (FR-2.1).
create table businesses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  type business_type not null,
  sector text,
  postcode text,
  tier tier not null default 'starter',
  subscription_state subscription_state not null default 'trialing',
  trial_ends_at timestamptz,
  stripe_customer_id text,
  -- Server-side journey persistence (FR-8.6 save-and-resume). Per-flow state
  -- lives here so a killed tab resumes exactly where it left off.
  journey_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Membership scopes every tenant RLS check. A first-time employer is a single
-- owner today; the table generalises to Growth-tier team members and future
-- accountant read-only shares without reworking policies.
create table business_members (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  profile_id uuid not null references profiles(id) on delete cascade,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  unique (business_id, profile_id)
);
create index business_members_profile_idx on business_members(profile_id);
create index business_members_business_idx on business_members(business_id);

-- employees: age band is DERIVED from dob in rules code, never stored
-- (CLAUDE.md §5). is_apprentice matters for the wage floor (Liam gotcha).
create table employees (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  full_name text not null,
  dob date,
  is_apprentice boolean not null default false,
  apprenticeship_start date,
  start_date date,
  pay_amount numeric(10,2),
  pay_period pay_period,
  weekly_hours numeric(6,2),
  status employee_status not null default 'prospective',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index employees_business_idx on employees(business_id);

create trigger profiles_set_updated_at before update on profiles
  for each row execute function public.set_updated_at();
create trigger businesses_set_updated_at before update on businesses
  for each row execute function public.set_updated_at();
create trigger employees_set_updated_at before update on employees
  for each row execute function public.set_updated_at();

-- ============================================================
-- 0003_config_versions.sql
-- ============================================================
-- 0003 — config_versions: the ONLY home for statutory values (CLAUDE.md Rule 4)
-- Global (not tenant-scoped). Read exclusively via getLiveConfig() in lib/config.
-- Written only by admins (service_role); no authenticated write policy.

create table config_versions (
  id uuid primary key default gen_random_uuid(),
  label text not null unique,              -- e.g. "2026.2"
  effective_from date not null,            -- statutory effect date
  status config_status not null default 'draft',
  values jsonb not null,                   -- the full statutory snapshot
  audit_note text,
  published_by uuid references profiles(id),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Resolution is by effective date; index supports "latest effective_from <= d".
create index config_versions_effective_idx on config_versions(effective_from desc);

-- At most one row may be flagged the canonical 'live' pointer per label set.
-- (Resolution itself is date-based; this simply guards the workflow state.)
create index config_versions_status_idx on config_versions(status);

create trigger config_versions_set_updated_at before update on config_versions
  for each row execute function public.set_updated_at();

-- ============================================================
-- 0004_compliance_tables.sql
-- ============================================================
-- 0004 — compliance tables: evidence, determinations, documents,
-- examinations, obligations, rtw_records.
-- determinations / examinations / rtw_records are IMMUTABLE (append-only).
-- Immutability triggers are attached in 0007.

-- evidence: unified store for uploaded artefacts. retention_class governs
-- deletion on account closure (skill gotcha #3).
create table evidence (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  type text not null,
  file_path text,                       -- private storage bucket key
  meta jsonb not null default '{}'::jsonb,
  retention_class retention_class not null default 'standard',
  created_at timestamptz not null default now()
);
create index evidence_business_idx on evidence(business_id);

-- determinations: immutable employment-status verdicts (FR-1.4).
-- Reasoning is template-assembled from factors, never LLM-written.
create table determinations (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references employees(id) on delete cascade,
  answers jsonb not null,
  verdict determination_verdict not null,
  confidence_band confidence_band not null,
  factors jsonb not null default '[]'::jsonb,
  rules_version text not null,
  reference text not null unique,       -- FE-DET-YYYY-NNNN
  pdf_path text,
  created_at timestamptz not null default now()
);
create index determinations_employee_idx on determinations(employee_id);

-- documents: version-chained artefacts. supersedes points at the prior version.
create table documents (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  employee_id uuid references employees(id) on delete set null,
  type document_type not null,
  status document_status not null default 'draft',
  version integer not null default 1,
  supersedes uuid references documents(id),
  content_path text,
  questionnaire jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index documents_business_idx on documents(business_id);
create index documents_employee_idx on documents(employee_id);

create trigger documents_set_updated_at before update on documents
  for each row execute function public.set_updated_at();

-- examinations: immutable examiner verdicts (FR-3.4/3.5/3.7). One row per
-- attempt. checklist_hash + versions are the VerificationSeal content.
create table examinations (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references documents(id) on delete cascade,
  attempt integer not null,
  verdict examination_verdict not null,
  checks jsonb not null default '[]'::jsonb,   -- 13 checks: {id,name,status,detail,statutoryRef}
  defects jsonb not null default '[]'::jsonb,  -- {clauseRef,issue,statutoryBasis,suggestedFix}
  generator_version text not null,
  examiner_version text not null,
  config_version text not null,                -- config label live at exam time
  checklist_hash text not null,
  created_at timestamptz not null default now(),
  unique (document_id, attempt)
);
create index examinations_document_idx on examinations(document_id);

-- obligations: the dashboard's engine (FR-5.1). Mutable state machine; rows are
-- re-derived and their state advances. due_date drives DeadlineChip grading.
create table obligations (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  employee_id uuid references employees(id) on delete cascade,
  type obligation_type not null,
  state obligation_state not null default 'not_started',
  due_date date,
  source text,                          -- what created/updates this obligation
  evidence_id uuid references evidence(id) on delete set null,
  document_id uuid references documents(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index obligations_business_idx on obligations(business_id);
create index obligations_employee_idx on obligations(employee_id);
create index obligations_due_idx on obligations(due_date);

create trigger obligations_set_updated_at before update on obligations
  for each row execute function public.set_updated_at();

-- rtw_records: immutable statutory-excuse evidence (FR-4.3). Re-checks create a
-- new row and link via supersedes; nothing is ever overwritten.
create table rtw_records (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references employees(id) on delete cascade,
  route rtw_route not null,
  checked_by text,
  checked_at timestamptz not null default now(),
  result rtw_result not null,
  evidence_id uuid references evidence(id) on delete set null,
  evidence_paths jsonb not null default '[]'::jsonb,
  expiry_date date,
  follow_up_due date,
  supersedes uuid references rtw_records(id),
  created_at timestamptz not null default now()
);
create index rtw_records_employee_idx on rtw_records(employee_id);

-- ============================================================
-- 0005_assistant_and_events.sql
-- ============================================================
-- 0005 — AI assistant threads/messages and the append-only audit log

-- assistant_threads: one conversation per row (Module 6).
create table assistant_threads (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index assistant_threads_business_idx on assistant_threads(business_id);

create trigger assistant_threads_set_updated_at before update on assistant_threads
  for each row execute function public.set_updated_at();

-- assistant_messages: every answer carries grounding_refs so the UI can render
-- source chips; an ungrounded statutory claim must signpost, not improvise.
create table assistant_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references assistant_threads(id) on delete cascade,
  role text not null,                   -- 'user' | 'assistant'
  content text not null,
  grounding_refs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index assistant_messages_thread_idx on assistant_messages(thread_id);

-- events: append-only audit log (CLAUDE.md Rule 5). Immutable (trigger in 0007).
create table events (
  id uuid primary key default gen_random_uuid(),
  business_id uuid references businesses(id) on delete cascade,
  actor_kind event_actor_kind not null default 'system',
  actor_id uuid,
  action text not null,
  entity text,
  entity_id uuid,
  payload jsonb not null default '{}'::jsonb,
  at timestamptz not null default now()
);
create index events_business_idx on events(business_id);
create index events_at_idx on events(at desc);

-- ============================================================
-- 0006_rls.sql
-- ============================================================
-- 0006 — Row Level Security. Every table scoped to business membership.
-- Immutable tables (determinations, examinations, rtw_records, events) get
-- SELECT + INSERT policies only; the absence of UPDATE/DELETE policies denies
-- those actions for authenticated, and 0007 adds triggers that also block
-- service_role. config_versions is global and admin-write-only.

-- ---- Tenant-RLS helper functions -------------------------------------------
-- Defined here (not 0001) because `language sql` bodies are validated at
-- creation time and these reference tables from 0002/0004. SECURITY DEFINER so
-- a policy can read business_members without recursing through its own RLS.
create or replace function public.is_member_of(target_business uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from business_members m
    where m.business_id = target_business
      and m.profile_id = auth.uid()
  );
$$;

create or replace function public.employee_business(target_employee uuid)
returns uuid
language sql
security definer
stable
set search_path = public
as $$
  select e.business_id from employees e where e.id = target_employee;
$$;

create or replace function public.document_business(target_document uuid)
returns uuid
language sql
security definer
stable
set search_path = public
as $$
  select d.business_id from documents d where d.id = target_document;
$$;

-- ---- Privilege grants (RLS then restricts within these) --------------------
grant usage on schema public to anon, authenticated, service_role;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;
grant all on all tables in schema public to service_role;

grant execute on function public.is_member_of(uuid) to anon, authenticated, service_role;
grant execute on function public.employee_business(uuid) to anon, authenticated, service_role;
grant execute on function public.document_business(uuid) to anon, authenticated, service_role;

-- ---- Enable RLS on everything ----------------------------------------------
alter table profiles            enable row level security;
alter table businesses          enable row level security;
alter table business_members    enable row level security;
alter table employees           enable row level security;
alter table config_versions     enable row level security;
alter table evidence            enable row level security;
alter table determinations      enable row level security;
alter table documents           enable row level security;
alter table examinations        enable row level security;
alter table obligations         enable row level security;
alter table rtw_records         enable row level security;
alter table assistant_threads   enable row level security;
alter table assistant_messages  enable row level security;
alter table events              enable row level security;

-- ---- profiles ---------------------------------------------------------------
create policy profiles_select on profiles for select using (id = auth.uid());
create policy profiles_insert on profiles for insert with check (id = auth.uid());
create policy profiles_update on profiles for update using (id = auth.uid()) with check (id = auth.uid());

-- ---- businesses -------------------------------------------------------------
-- Creation goes through a SECURITY DEFINER onboarding RPC (Prompt 3) / service
-- role so a business and its owner-membership are created atomically; there is
-- deliberately no authenticated INSERT policy here.
create policy businesses_select on businesses for select using (is_member_of(id));
create policy businesses_update on businesses for update using (is_member_of(id)) with check (is_member_of(id));

-- ---- business_members -------------------------------------------------------
create policy members_select on business_members for select
  using (profile_id = auth.uid() or is_member_of(business_id));

-- ---- employees --------------------------------------------------------------
-- No DELETE policy: employees are marked 'left', never hard-deleted (protects
-- the immutable determinations/rtw_records that reference them).
create policy employees_select on employees for select using (is_member_of(business_id));
create policy employees_insert on employees for insert with check (is_member_of(business_id));
create policy employees_update on employees for update using (is_member_of(business_id)) with check (is_member_of(business_id));

-- ---- config_versions (global, read-only to tenants; drafts hidden) ----------
create policy config_select on config_versions for select using (status <> 'draft');

-- ---- evidence ---------------------------------------------------------------
create policy evidence_select on evidence for select using (is_member_of(business_id));
create policy evidence_insert on evidence for insert with check (is_member_of(business_id));

-- ---- determinations (immutable) ---------------------------------------------
create policy determinations_select on determinations for select
  using (is_member_of(employee_business(employee_id)));
create policy determinations_insert on determinations for insert
  with check (is_member_of(employee_business(employee_id)));

-- ---- documents --------------------------------------------------------------
create policy documents_select on documents for select using (is_member_of(business_id));
create policy documents_insert on documents for insert with check (is_member_of(business_id));
create policy documents_update on documents for update using (is_member_of(business_id)) with check (is_member_of(business_id));

-- ---- examinations (immutable) -----------------------------------------------
create policy examinations_select on examinations for select
  using (is_member_of(document_business(document_id)));
create policy examinations_insert on examinations for insert
  with check (is_member_of(document_business(document_id)));

-- ---- obligations ------------------------------------------------------------
create policy obligations_select on obligations for select using (is_member_of(business_id));
create policy obligations_insert on obligations for insert with check (is_member_of(business_id));
create policy obligations_update on obligations for update using (is_member_of(business_id)) with check (is_member_of(business_id));

-- ---- rtw_records (immutable) ------------------------------------------------
create policy rtw_select on rtw_records for select
  using (is_member_of(employee_business(employee_id)));
create policy rtw_insert on rtw_records for insert
  with check (is_member_of(employee_business(employee_id)));

-- ---- assistant_threads ------------------------------------------------------
create policy threads_select on assistant_threads for select using (is_member_of(business_id));
create policy threads_insert on assistant_threads for insert with check (is_member_of(business_id));
create policy threads_update on assistant_threads for update using (is_member_of(business_id)) with check (is_member_of(business_id));

-- ---- assistant_messages -----------------------------------------------------
create policy messages_select on assistant_messages for select
  using (is_member_of((select t.business_id from assistant_threads t where t.id = thread_id)));
create policy messages_insert on assistant_messages for insert
  with check (is_member_of((select t.business_id from assistant_threads t where t.id = thread_id)));

-- ---- events (immutable, append-only) ----------------------------------------
create policy events_select on events for select using (is_member_of(business_id));
create policy events_insert on events for insert with check (is_member_of(business_id));

-- ============================================================
-- 0007_immutability.sql
-- ============================================================
-- 0007 — hard immutability for evidence tables (CLAUDE.md Rule 5).
-- These triggers block UPDATE and DELETE for EVERY role, including service_role
-- and the table owner — a guarantee RLS alone cannot make. Inserts are allowed;
-- corrections happen by appending a new row (rtw re-checks, document versions).

create trigger determinations_immutable
  before update or delete on determinations
  for each row execute function public.forbid_mutation();

create trigger examinations_immutable
  before update or delete on examinations
  for each row execute function public.forbid_mutation();

create trigger rtw_records_immutable
  before update or delete on rtw_records
  for each row execute function public.forbid_mutation();

create trigger events_immutable
  before update or delete on events
  for each row execute function public.forbid_mutation();

-- ============================================================
-- 0008_onboarding_rpc.sql
-- ============================================================
-- 0008 — onboarding RPC: create a business and its owner membership atomically.
-- There is deliberately no authenticated INSERT policy on businesses /
-- business_members (see DECISIONS.md P02); creation goes through this
-- SECURITY DEFINER function so a business always has exactly one owner row and a
-- user can never insert a membership into someone else's business.

create or replace function public.create_business_with_owner(
  p_name text,
  p_type business_type,
  p_sector text default null,
  p_tier tier default 'starter',
  p_journey jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_business_id uuid;
begin
  if v_uid is null then
    raise exception 'not authenticated' using errcode = 'insufficient_privilege';
  end if;

  -- Ensure the caller has a profile row (first sign-in).
  insert into profiles (id) values (v_uid) on conflict (id) do nothing;

  insert into businesses (name, type, sector, tier, subscription_state, trial_ends_at, journey_state)
  values (p_name, p_type, p_sector, p_tier, 'trialing', now() + interval '7 days', coalesce(p_journey, '{}'::jsonb))
  returning id into v_business_id;

  insert into business_members (business_id, profile_id, role)
  values (v_business_id, v_uid, 'owner');

  insert into events (business_id, actor_kind, actor_id, action, entity, entity_id)
  values (v_business_id, 'user', v_uid, 'business.created', 'business', v_business_id);

  return v_business_id;
end;
$$;

grant execute on function public.create_business_with_owner(text, business_type, text, tier, jsonb)
  to authenticated;

-- ============================================================
-- 0009_onboarding_state.sql
-- ============================================================
-- 0009 — per-user onboarding draft state (save-and-resume, FR-8.6).
-- The onboarding flow persists step + answers here BEFORE a business exists
-- (the gap-check path only creates the business at the end). Once the business
-- is created, its own journey_state takes over and this is cleared.
-- profiles already has select/insert/update policies scoped to id = auth.uid(),
-- so the authenticated client can persist this directly under RLS.

alter table profiles add column onboarding_state jsonb not null default '{}'::jsonb;

-- ============================================================
-- 0010_determination_reference.sql
-- ============================================================
-- 0010 — determination reference sequence + minting function.
-- References are FE-DET-YYYY-NNNN, globally unique. A SECURITY DEFINER function
-- mints them from a sequence so concurrent determinations never collide, and so
-- the numeric run can't be inferred/forged per-tenant.

create sequence if not exists determination_ref_seq;

create or replace function public.mint_determination_reference()
returns text
language sql
security definer
set search_path = public
as $$
  select 'FE-DET-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('determination_ref_seq')::text, 4, '0');
$$;

grant execute on function public.mint_determination_reference() to authenticated;
