-- GENERATED by scripts/gen-seed.mjs — do not edit by hand.
-- Source of statutory values: lib/config/versions.json
-- Regenerate: pnpm gen:seed

-- ===== Statutory configuration versions =====
insert into config_versions (label, effective_from, status, values, audit_note)
values ('2026.1', '2025-04-01', 'superseded', '{"minimum_wage":{"nlw_21_plus":12.21,"nmw_18_20":10,"nmw_16_17":7.55,"apprentice":7.55},"holiday":{"statutory_weeks":5.6,"pay_record_retention_years":6},"pension":{"ae_earnings_trigger":10000,"qualifying_band_lower":6240,"qualifying_band_upper":50270,"min_total_contribution_pct":8,"min_employer_contribution_pct":3,"declaration_of_compliance_months":5},"insurance":{"el_min_cover":5000000,"el_penalty_per_day":2500},"ssp":{"day_one":false},"right_to_work":{"penalty_first_breach":45000,"penalty_repeat_breach":60000},"employment_penalties":{"tpr_auto_enrolment_fixed":400,"written_statement_tribunal_weeks":4,"pay_record_retention_years":3}}'::jsonb, 'April 2025 statutory rates (2025/26 regime). Retained deliberately as the canonical uprating fixture: the 2026.1 -> 2026.2 transition (NLW 12.21 -> 12.71) drives the J4 golden suite.')
on conflict (label) do update set effective_from = excluded.effective_from, status = excluded.status, values = excluded.values, audit_note = excluded.audit_note;

insert into config_versions (label, effective_from, status, values, audit_note)
values ('2026.2', '2026-04-01', 'live', '{"minimum_wage":{"nlw_21_plus":12.71,"nmw_18_20":10.85,"nmw_16_17":8,"apprentice":8},"holiday":{"statutory_weeks":5.6,"pay_record_retention_years":6},"pension":{"ae_earnings_trigger":10000,"qualifying_band_lower":6240,"qualifying_band_upper":50270,"min_total_contribution_pct":8,"min_employer_contribution_pct":3,"declaration_of_compliance_months":5},"insurance":{"el_min_cover":5000000,"el_penalty_per_day":2500},"ssp":{"day_one":true},"right_to_work":{"penalty_first_breach":45000,"penalty_repeat_breach":60000},"employment_penalties":{"tpr_auto_enrolment_fixed":400,"written_statement_tribunal_weeks":4,"pay_record_retention_years":3}}'::jsonb, 'April 2026 statutory rates. NLW rises to 12.71; 18-20 to 10.85; 16-17/apprentice to 8.00. Day-one SSP begins (ERA 2025). AE thresholds held at 2025/26 levels.')
on conflict (label) do update set effective_from = excluded.effective_from, status = excluded.status, values = excluded.values, audit_note = excluded.audit_note;

-- ===== Demo tenant 1: canonical scenario =====
-- Dave Okonkwo · DO Plumbing & Heating Ltd (limited, Walsall)
-- hiring Liam Carter, apprentice plumber, £8.00/hr, 40 hrs/wk, start 2026-08-03.
insert into auth.users (id, email) values ('00000000-0000-4000-8000-000000000001', 'dave@doplumbing.example') on conflict (id) do nothing;
insert into profiles (id, full_name) values ('00000000-0000-4000-8000-000000000001', 'Dave Okonkwo') on conflict (id) do nothing;
insert into businesses (id, name, type, sector, postcode, tier, subscription_state)
values ('00000000-0000-4000-8000-0000000000b1', 'DO Plumbing & Heating Ltd', 'limited', 'Trades', 'WS1 1AA', 'launch', 'trialing') on conflict (id) do nothing;
insert into business_members (id, business_id, profile_id, role) values ('00000000-0000-4000-8000-0000000000c1', '00000000-0000-4000-8000-0000000000b1', '00000000-0000-4000-8000-000000000001', 'owner') on conflict (id) do nothing;
insert into employees (id, business_id, full_name, dob, is_apprentice, apprenticeship_start, start_date, pay_amount, pay_period, weekly_hours, status)
values ('00000000-0000-4000-8000-0000000000e1', '00000000-0000-4000-8000-0000000000b1', 'Liam Carter', '1999-05-14', true, '2026-08-03', '2026-08-03', 8.00, 'hourly', 40, 'prospective') on conflict (id) do nothing;

-- ===== Demo tenant 2: isolation fixture for the RLS cross-tenant test =====
insert into auth.users (id, email) values ('00000000-0000-4000-8000-000000000002', 'sarah@brightlights.example') on conflict (id) do nothing;
insert into profiles (id, full_name) values ('00000000-0000-4000-8000-000000000002', 'Sarah Bright') on conflict (id) do nothing;
insert into businesses (id, name, type, sector, postcode, tier, subscription_state)
values ('00000000-0000-4000-8000-0000000000b2', 'Bright Lights Salon', 'sole_trader', 'Hair & Beauty', 'B1 2BB', 'starter', 'trialing') on conflict (id) do nothing;
insert into business_members (id, business_id, profile_id, role) values ('00000000-0000-4000-8000-0000000000c2', '00000000-0000-4000-8000-0000000000b2', '00000000-0000-4000-8000-000000000002', 'owner') on conflict (id) do nothing;
insert into employees (id, business_id, full_name, dob, is_apprentice, start_date, pay_amount, pay_period, weekly_hours, status)
values ('00000000-0000-4000-8000-0000000000e2', '00000000-0000-4000-8000-0000000000b2', 'Priya Shah', '2003-02-20', false, '2026-05-01', 12.71, 'hourly', 30, 'active') on conflict (id) do nothing;
