import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

/**
 * Server-rendered employment-contract PDF, stamped with the examiner seal
 * (timestamp + checklist hash). A contract is EXAMINED, so — unlike the
 * determination — it carries a VerificationSeal, not a rules-engine version.
 * Only ever call this for a document with a recorded examiner PASS.
 */
export interface ContractClausePdf {
  heading: string;
  statutoryRef?: string;
  body: string;
}

export interface ContractPdfData {
  title: string;
  employerName: string;
  employeeName: string;
  clauses: ContractClausePdf[];
  seal: { timestamp: string; hash: string };
  examinerVersion: string;
  configVersion: string;
}

const INK = "#0E1B2C";
const GREEN = "#178055";
const NEUTRAL = "#5A626C";
const HAIRLINE = "#D8D3C8";

const s = StyleSheet.create({
  page: { padding: 48, fontFamily: "Helvetica", fontSize: 10, color: INK, backgroundColor: "#FDFBF5" },
  kicker: { fontSize: 8, letterSpacing: 1.5, color: NEUTRAL, textTransform: "uppercase", marginBottom: 6 },
  title: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  intro: { fontSize: 10, color: NEUTRAL, marginBottom: 14, lineHeight: 1.5 },
  sealBox: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1, borderColor: GREEN, borderRadius: 6, padding: 12, marginBottom: 20, backgroundColor: "#E4F3EC" },
  sealLabel: { fontSize: 8, letterSpacing: 1, color: GREEN, textTransform: "uppercase", marginBottom: 3 },
  sealValue: { fontSize: 11, fontFamily: "Helvetica-Bold", color: GREEN },
  sealMeta: { fontSize: 8, color: NEUTRAL, marginTop: 2 },
  clause: { borderTopWidth: 0.5, borderTopColor: HAIRLINE, paddingVertical: 9 },
  clauseHead: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 3 },
  clauseBody: { fontSize: 10, lineHeight: 1.5, color: "#2E3947" },
  clauseRef: { fontSize: 8, color: NEUTRAL, marginTop: 3, fontFamily: "Helvetica-Oblique" },
  footer: { marginTop: 18, borderTopWidth: 0.5, borderTopColor: HAIRLINE, paddingTop: 10, fontSize: 8, color: NEUTRAL, lineHeight: 1.4 },
});

function ContractDoc({ d }: { d: ContractPdfData }) {
  return (
    <Document title={d.title}>
      <Page size="A4" style={s.page}>
        <Text style={s.kicker}>Contract of employment · Written statement of particulars</Text>
        <Text style={s.title}>{d.employerName} and {d.employeeName}</Text>
        <Text style={s.intro}>
          Given under the Employment Rights Act 1996. Every clause below was checked against the 13 statutory
          requirements by the FirstEmployer Examiner before this document was released.
        </Text>

        <View style={s.sealBox}>
          <View>
            <Text style={s.sealLabel}>Examiner verified</Text>
            <Text style={s.sealValue}>Passed all 13 statutory checks</Text>
            <Text style={s.sealMeta}>{d.seal.timestamp} · {d.examinerVersion} · config {d.configVersion}</Text>
          </View>
          <View>
            <Text style={s.sealLabel}>Seal</Text>
            <Text style={s.sealValue}>{d.seal.hash}</Text>
          </View>
        </View>

        {d.clauses.map((c, i) => (
          <View key={i} style={s.clause} wrap={false}>
            <Text style={s.clauseHead}>{c.heading}</Text>
            <Text style={s.clauseBody}>{c.body}</Text>
            {c.statutoryRef ? <Text style={s.clauseRef}>{c.statutoryRef}</Text> : null}
          </View>
        ))}

        <Text style={s.footer}>
          This document is the employee&apos;s written statement of employment particulars. It was generated by
          FirstEmployer and independently examined against the Employment Rights Act 1996 s.1 (as amended) and related
          law. Examiner seal {d.seal.hash}, {d.seal.timestamp}. Statutory rates applied from config {d.configVersion}.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderContractPdf(d: ContractPdfData): Promise<Buffer> {
  return renderToBuffer(<ContractDoc d={d} />);
}
