// Generates supabase/seed.sql from lib/config/versions.json (the single source
// of truth for statutory config) plus the canonical Dave/Liam demo scenario and
// a second tenant used by the RLS cross-tenant test.
//
// Run: node scripts/gen-seed.mjs   (or: pnpm gen:seed)

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const versions = JSON.parse(readFileSync(join(root, "lib/config/versions.json"), "utf8")).versions;

const sqlStr = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const sqlJson = (o) => `'${JSON.stringify(o).replace(/'/g, "''")}'::jsonb`;

// Fixed UUIDs — deterministic seed for reproducible tests and demos.
const ID = {
  daveUser: "00000000-0000-4000-8000-000000000001",
  sarahUser: "00000000-0000-4000-8000-000000000002",
  doPlumbing: "00000000-0000-4000-8000-0000000000b1",
  salon: "00000000-0000-4000-8000-0000000000b2",
  daveMember: "00000000-0000-4000-8000-0000000000c1",
  sarahMember: "00000000-0000-4000-8000-0000000000c2",
  liam: "00000000-0000-4000-8000-0000000000e1",
  priya: "00000000-0000-4000-8000-0000000000e2",
};

const lines = [];
lines.push("-- GENERATED by scripts/gen-seed.mjs — do not edit by hand.");
lines.push("-- Source of statutory values: lib/config/versions.json");
lines.push("-- Regenerate: pnpm gen:seed");
lines.push("");

lines.push("-- ===== Statutory configuration versions =====");
for (const v of versions) {
  lines.push(
    `insert into config_versions (label, effective_from, status, values, audit_note)`,
  );
  lines.push(
    `values (${sqlStr(v.label)}, ${sqlStr(v.effective_from)}, ${sqlStr(v.status)}, ${sqlJson(
      v.values,
    )}, ${sqlStr(v.audit_note ?? null)})`,
  );
  // Upsert so re-seeding propagates statutory-config edits to the DB.
  lines.push(
    `on conflict (label) do update set effective_from = excluded.effective_from, status = excluded.status, values = excluded.values, audit_note = excluded.audit_note;`,
  );
  lines.push("");
}

lines.push("-- ===== Demo tenant 1: canonical scenario =====");
lines.push("-- Dave Okonkwo · DO Plumbing & Heating Ltd (limited, Walsall)");
lines.push("-- hiring Liam Carter, apprentice plumber, £8.00/hr, 40 hrs/wk, start 2026-08-03.");
lines.push(
  `insert into auth.users (id, email) values (${sqlStr(ID.daveUser)}, 'dave@doplumbing.example') on conflict (id) do nothing;`,
);
lines.push(
  `insert into profiles (id, full_name) values (${sqlStr(ID.daveUser)}, 'Dave Okonkwo') on conflict (id) do nothing;`,
);
lines.push(
  `insert into businesses (id, name, type, sector, postcode, tier, subscription_state)`,
);
lines.push(
  `values (${sqlStr(ID.doPlumbing)}, 'DO Plumbing & Heating Ltd', 'limited', 'Trades', 'WS1 1AA', 'launch', 'trialing') on conflict (id) do nothing;`,
);
lines.push(
  `insert into business_members (id, business_id, profile_id, role) values (${sqlStr(
    ID.daveMember,
  )}, ${sqlStr(ID.doPlumbing)}, ${sqlStr(ID.daveUser)}, 'owner') on conflict (id) do nothing;`,
);
lines.push(
  `insert into employees (id, business_id, full_name, dob, is_apprentice, apprenticeship_start, start_date, pay_amount, pay_period, weekly_hours, status)`,
);
lines.push(
  `values (${sqlStr(ID.liam)}, ${sqlStr(ID.doPlumbing)}, 'Liam Carter', '1999-05-14', true, '2026-08-03', '2026-08-03', 8.00, 'hourly', 40, 'prospective') on conflict (id) do nothing;`,
);
lines.push("");

lines.push("-- ===== Demo tenant 2: isolation fixture for the RLS cross-tenant test =====");
lines.push(
  `insert into auth.users (id, email) values (${sqlStr(ID.sarahUser)}, 'sarah@brightlights.example') on conflict (id) do nothing;`,
);
lines.push(
  `insert into profiles (id, full_name) values (${sqlStr(ID.sarahUser)}, 'Sarah Bright') on conflict (id) do nothing;`,
);
lines.push(
  `insert into businesses (id, name, type, sector, postcode, tier, subscription_state)`,
);
lines.push(
  `values (${sqlStr(ID.salon)}, 'Bright Lights Salon', 'sole_trader', 'Hair & Beauty', 'B1 2BB', 'starter', 'trialing') on conflict (id) do nothing;`,
);
lines.push(
  `insert into business_members (id, business_id, profile_id, role) values (${sqlStr(
    ID.sarahMember,
  )}, ${sqlStr(ID.salon)}, ${sqlStr(ID.sarahUser)}, 'owner') on conflict (id) do nothing;`,
);
lines.push(
  `insert into employees (id, business_id, full_name, dob, is_apprentice, start_date, pay_amount, pay_period, weekly_hours, status)`,
);
lines.push(
  `values (${sqlStr(ID.priya)}, ${sqlStr(ID.salon)}, 'Priya Shah', '2003-02-20', false, '2026-05-01', 12.71, 'hourly', 30, 'active') on conflict (id) do nothing;`,
);
lines.push("");

writeFileSync(join(root, "supabase/seed.sql"), lines.join("\n"));
console.log("Wrote supabase/seed.sql");

// Export the fixed IDs for the test harness.
writeFileSync(
  join(root, "supabase/tests/seed-ids.json"),
  JSON.stringify(ID, null, 2) + "\n",
);
console.log("Wrote supabase/tests/seed-ids.json");
